// Generated by scripts/process-assets.mjs — do not edit by hand.
export const heroBlurDataURL = "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACQBACdASoYABIAPu1mqk+ppSOmsBgIATAdiWQArDLogOLFIDqznC1obIY3xAAA+pQmbhO4o2X2RtGbskuzMMGIA+9s0wfX+AtpFohuB5J5Dd+EriW5uZB299cxO3rxp69/GLCQ3SZoF1HFOKTQLL5QAAA=";
export const heroAspectRatio = 1.3333;
