// @ts-check
/**
 * Prime Cane — asset pipeline (LOCAL build tool, not run in CI).
 *
 * Produces, from the brand source files in ~/Downloads:
 *   1. Hero image  — extracts the cane-field photo from the brand PDF, emits
 *      responsive WebP + JPEG variants and a base64 LQIP blur module.
 *   2. Favicons    — full package from the cane-disc icon.svg (favicon.svg/.ico,
 *      apple-touch-icon, icon-192/512, favicon-32) on the brand-green backing.
 *   3. OG card     — 1200x630 social-share image (green + emblem + strapline).
 *
 * The OPTIMISED OUTPUTS are committed to the repo; the heavy sources are not.
 * CI/Cloudflare therefore never needs poppler or the source PDF.
 *
 * Tools: sharp (libvips) + png-to-ico + poppler (pdfimages), all local.
 * Usage:  npm run assets    (override source with HERO_PDF=/path/to.pdf)
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import sharp from "sharp";
import pngToIco from "png-to-ico";

const ROOT = new URL("..", import.meta.url).pathname;
const SRC_LOGOS = join(ROOT, "src/assets/logos");
const OUT_HERO = join(ROOT, "src/assets/hero");
const OUT_PRODUCTS = join(ROOT, "src/assets/products");
const OUT_PUBLIC = join(ROOT, "public");

const GREEN = "#184D2A";
const GREEN_NIGHT = "#0A2414";
const LIME = "#D7DF23";
const CREAM = "#FDFDFD";

const HERO_PDF =
  process.env.HERO_PDF || join(homedir(), "Downloads", "Prime Cane - Logo.pdf");

const log = (msg) => console.log(`  ${msg}`);

/* ------------------------------------------------------------------ */
/* 1. HERO IMAGE                                                       */
/* ------------------------------------------------------------------ */
async function buildHero() {
  console.log("\n• Hero image");
  mkdirSync(OUT_HERO, { recursive: true });

  // Extract the cane-field photo (page 4, the single large RGB image) via poppler.
  const work = join(tmpdir(), "pc-hero");
  rmSync(work, { recursive: true, force: true });
  mkdirSync(work, { recursive: true });
  if (!existsSync(HERO_PDF)) {
    throw new Error(
      `Hero source PDF not found at "${HERO_PDF}". Set HERO_PDF=/path/to/pdf.`,
    );
  }
  execFileSync("pdfimages", ["-png", "-f", "4", "-l", "4", HERO_PDF, join(work, "p")]);
  const extracted = join(work, "p-000.png");
  if (!existsSync(extracted)) throw new Error("pdfimages did not produce the hero image");

  const meta = await sharp(extracted).metadata();
  log(`source ${meta.width}x${meta.height}`);

  // Responsive variants — never upscale beyond source width.
  const widths = [1440, 768].filter((w) => w <= (meta.width ?? 0)).concat(
    (meta.width ?? 0) < 1440 ? [meta.width ?? 1440] : [],
  );
  const uniqueWidths = [...new Set(widths)].sort((a, b) => b - a);

  for (const w of uniqueWidths) {
    const base = sharp(extracted).resize({ width: w, withoutEnlargement: true });
    await base
      .clone()
      .webp({ quality: w > 1000 ? 68 : 68, effort: 6 })
      .toFile(join(OUT_HERO, `field-${w}.webp`));
    await base
      .clone()
      .jpeg({ quality: w > 1000 ? 74 : 70, mozjpeg: true })
      .toFile(join(OUT_HERO, `field-${w}.jpg`));
    log(`field-${w}.{webp,jpg}`);
  }

  // LQIP blur — tiny base64 inlined as a CSS background while the hero loads.
  const lqip = await sharp(extracted)
    .resize({ width: 24 })
    .blur(1)
    .webp({ quality: 40 })
    .toBuffer();
  const dataURL = `data:image/webp;base64,${lqip.toString("base64")}`;
  const ratio = (meta.width ?? 4) / (meta.height ?? 3);
  writeFileSync(
    join(OUT_HERO, "blur.ts"),
    `// Generated by scripts/process-assets.mjs — do not edit by hand.\n` +
      `export const heroBlurDataURL = ${JSON.stringify(dataURL)};\n` +
      `export const heroAspectRatio = ${ratio.toFixed(4)};\n`,
  );
  log(`blur.ts (${(lqip.length / 1024).toFixed(1)}KB inlined)`);
}

/* ------------------------------------------------------------------ */
/* 1b. FLAGSHIP PRODUCT (packaged sugar, page 3 — transparent cut-out) */
/* ------------------------------------------------------------------ */
async function buildSugarPack() {
  console.log("\n• Flagship product (sugar pack)");
  mkdirSync(OUT_PRODUCTS, { recursive: true });

  const work = join(tmpdir(), "pc-pack");
  rmSync(work, { recursive: true, force: true });
  mkdirSync(work, { recursive: true });
  // Page 3 holds the packaging renders; object 6 is the angled 2kg bag, with
  // its soft mask (object 7) immediately after — extracted as p-000 / p-001.
  execFileSync("pdfimages", ["-png", "-f", "3", "-l", "3", HERO_PDF, join(work, "p")]);
  const rgb = join(work, "p-000.png");
  const mask = join(work, "p-001.png");
  if (!existsSync(rgb) || !existsSync(mask)) {
    throw new Error("Could not extract the sugar-pack image + mask from page 3");
  }

  // Apply the PDF soft mask (white = bag, black = background) as the alpha
  // channel → true transparent cut-out. rgb is opaque 3-channel; the mask is
  // forced to exactly match its dimensions as a single raw channel.
  const { width, height } = await sharp(rgb).metadata();
  const maskBuf = await sharp(mask)
    .greyscale()
    .resize(width, height, { fit: "fill" })
    .raw()
    .toBuffer();
  const cut = await sharp(rgb)
    .joinChannel(maskBuf, { raw: { width, height, channels: 1 } })
    .png() // clean RGBA intermediate
    .toBuffer();

  await sharp(cut)
    .resize({ width: 600, withoutEnlargement: true })
    .webp({ quality: 86, alphaQuality: 100, effort: 6 })
    .toFile(join(OUT_PRODUCTS, "sugar-pack.webp"));
  const meta = await sharp(join(OUT_PRODUCTS, "sugar-pack.webp")).metadata();
  if (!meta.hasAlpha) throw new Error("sugar-pack.webp lost its alpha channel");
  log(`sugar-pack.webp (${meta.width}x${meta.height}, transparent)`);
}

/* ------------------------------------------------------------------ */
/* 2. FAVICONS  (following favicon-gen skill workflow)                 */
/* ------------------------------------------------------------------ */
async function buildFavicons() {
  console.log("\n• Favicons");
  const iconSvg = readFileSync(join(SRC_LOGOS, "icon.svg"), "utf8");

  // Wrap the cane disc on a rounded brand-green backing so the cream + lime
  // marks stay legible on any tab colour, and iOS never shows a black square.
  const vb = iconSvg.match(/viewBox="([\d.\s]+)"/);
  const [, , vw = "133.78", vh = "134.73"] = (vb?.[1] ?? "0 0 133.78 134.73").split(/\s+/);
  const pad = 14;
  const W = Number(vw) + pad * 2;
  const H = Number(vh) + pad * 2;
  const wrapped = iconSvg
    .replace(/viewBox="[\d.\s]+"/, `viewBox="${-pad} ${-pad} ${W} ${H}"`)
    .replace(
      /<\/defs>/,
      `</defs>\n  <rect x="${-pad}" y="${-pad}" width="${W}" height="${H}" rx="${W * 0.22}" fill="${GREEN}"/>`,
    );

  writeFileSync(join(OUT_PUBLIC, "favicon.svg"), wrapped);
  log("favicon.svg");

  const render = (size) =>
    sharp(Buffer.from(wrapped), { density: Math.max(384, size * 4) })
      .resize(size, size)
      .png();

  // .ico (16 + 32 + 48)
  const icoBufs = await Promise.all([16, 32, 48].map((s) => render(s).toBuffer()));
  writeFileSync(join(OUT_PUBLIC, "favicon.ico"), await pngToIco(icoBufs));
  log("favicon.ico (16/32/48)");

  await render(32).toFile(join(OUT_PUBLIC, "favicon-32.png"));
  await render(180).toFile(join(OUT_PUBLIC, "apple-touch-icon.png")); // solid bg already
  await render(192).toFile(join(OUT_PUBLIC, "icon-192.png"));
  await render(512).toFile(join(OUT_PUBLIC, "icon-512.png"));
  log("favicon-32 / apple-touch-icon / icon-192 / icon-512");
}

/* ------------------------------------------------------------------ */
/* 3. OPEN GRAPH CARD  (1200x630)                                      */
/* ------------------------------------------------------------------ */
async function buildOgCard() {
  console.log("\n• Open Graph card");
  const W = 1200;
  const H = 630;

  const bg = Buffer.from(`
    <svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
      <defs>
        <radialGradient id="g" cx="50%" cy="34%" r="75%">
          <stop offset="0%" stop-color="${GREEN}"/>
          <stop offset="100%" stop-color="${GREEN_NIGHT}"/>
        </radialGradient>
      </defs>
      <rect width="${W}" height="${H}" fill="url(#g)"/>
      <text x="${W / 2}" y="${H - 78}" text-anchor="middle"
            font-family="Hanken Grotesk, Arial, sans-serif" font-size="32"
            letter-spacing="12" font-weight="700" fill="${LIME}">PURE · NATURAL · PREMIUM</text>
      <text x="${W / 2}" y="${H - 38}" text-anchor="middle"
            font-family="Hanken Grotesk, Arial, sans-serif" font-size="22"
            letter-spacing="2" fill="${CREAM}" opacity="0.72">primecane.com · Chiredzi, Zimbabwe</text>
    </svg>`);

  const logoW = 330;
  const logo = await sharp(join(SRC_LOGOS, "Logo_sec.svg"), { density: 384 })
    .resize({ width: logoW })
    .png()
    .toBuffer();
  const logoMeta = await sharp(logo).metadata();

  await sharp(bg)
    .composite([{ input: logo, top: 70, left: Math.round((W - (logoMeta.width ?? logoW)) / 2) }])
    .png()
    .toFile(join(OUT_PUBLIC, "og-image.png"));
  log("og-image.png (1200x630)");
}

/* ------------------------------------------------------------------ */
async function main() {
  console.log("Prime Cane — processing brand assets");
  await buildHero();
  await buildSugarPack();
  await buildFavicons();
  await buildOgCard();
  console.log("\n✓ Assets ready.\n");
}

main().catch((err) => {
  console.error("\n✗ Asset pipeline failed:\n", err);
  process.exit(1);
});
